CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_name VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(300) NOT NULL,
    status TINYINT NOT NULL,
    url VARCHAR(300),
    user_role VARCHAR(20) NOT NULL,

    PRIMARY KEY (id)
);
